[tool.black]
line-length = 88
target-version = ["py310"]

[tool.ruff]
line-length = 88
lint.select = ["ANN", "C", "E", "F", "W"]
lint.ignore = ["E501"]  # 긴 라인 제한 비활성화

[tool.ruff.lint.flake8-annotations]
suppress-dummy-args = false
suppress-none-returning = false
allow-star-arg-any = false
