"""
This script provides a utility function to visualize the results of a t-SNE
transformation. It plots the 2D data points generated by t-SNE and colors them according
to their labels. The resulting plot is saved as an image file.

Author: yumemonzo@gmail.com Date: 2024-12-19
"""

import numpy as np
import matplotlib.pyplot as plt


def plot_tsne(y: np.array, labels: np.array, filename: str = "tsne_result.jpg") -> None:
    """
    Plot the results of a t-SNE transformation and save the plot as an image.

    Parameters:
        y (Any): A 2D array containing the t-SNE transformed data points (shape: [n_samples, 2]).
        labels (Any): An array containing the labels corresponding to the data points.
        filename (str): The filename to save the plot as. Defaults to "tsne_result.jpg".

    Returns:
        None
    """
    plt.figure(figsize=(10, 8))
    scatter = plt.scatter(y[:, 0], y[:, 1], c=labels, cmap="tab10", s=10, alpha=0.7)
    plt.colorbar(scatter, label="Label")
    plt.title("t-SNE Result", fontsize=14)
    plt.axis("off")
    plt.savefig(filename, dpi=300)
    plt.close()
